// components/About.tsx
"use client"

import {motion} from "framer-motion"
import Image from "next/image"

const About = () => {
    
    const SKILLS = [
        "TypeScript",
        "Python",
        "Java",
        "NextJS",
        "Pandas",
        "HTML & CSS"
    ]


  return (
    <section className="flex min-h-screen bg-blue-highlight text-white flex-1 " id='about'>
        <div className="m-auto max-container padding-container mt-30 flex flex-col-reverse md:flex-row p-5">
            <div className='top-20 sm:sticky md:top-28 lg:top-32 md:w-1/2'>
                <h2 className='text-4xl mt-10 md:text-6xl font-bold capitalize'>A brief intro, who am I?</h2>
                <p className='text-lg mt-5'>I am currently a Research Analyst at ABI Research, working in the 5G, 6G & Open RAN Networks team. I have recently graduated with Bachelor of Science with Honours in Computer Science from Queen Mary, University of London.</p>
                <p className='text-lg mt-5'>When I am not working, I enjoy building websites from scratch, learning new technologies, playing chess, going to the gym and cooking new food from various cuisines.</p>
                <p className='text-lg mt-5'>Here are some of the technologies I am currently working with:</p>
                <div className="grid grid-cols-1 md:grid-cols-2">
                    {SKILLS.map((skill) => (
                        <motion.p 
                            key={skill} 
                            className='py-4 px-2 text-center text-xl md:text-3xl z-10 font-semibold'
                            whileHover={{ translateY: -10, transition: {
                                duration: 0.1, yoyo: "Infinity" 
                            }}}
                        >
                            {skill}
                        </motion.p>
                    ))}
                </div>
            </div>
            <div className='top-28 overflow-hidden rounded-md md:sticky md:w-1/2 flex justify-center items-center'>
                <Image src={"/larbi.jpg"} alt="Larbi at his graduation" width={450} height={300} className="rounded-md" />
            </div>
        </div>
    </section>
  )
}

export default About

// src/components/About.vue
<script setup lang="ts">
const SKILLS = ['TypeScript', 'Python', 'Java', 'Vue', 'Pandas', 'HTML & CSS']
</script>

<template>
  <section class="bg-deep border-y border-line" id="about">
    <div class="mx-auto max-w-5xl px-6 lg:px-8 py-24 md:py-32 flex flex-col-reverse md:flex-row gap-12 md:gap-16">
      <div class="md:w-3/5">
        <p class="text-[0.7rem] tracking-[0.35em] uppercase text-accent mb-4">
          About
        </p>
        <h2 class="text-3xl md:text-5xl font-light tracking-tight">
          A brief intro — who am I?
        </h2>
        <p class="text-lg text-muted mt-6">
          I am currently a Principal Analyst at ABI Research, leading the firm's Artificial Intelligence research — covering how AI is reshaping telecoms, cloud and enterprise technology. I previously spent time on ABI's 5G, 6G & Open RAN Networks team, and hold a Bachelor of Science with Honours in Computer Science from Queen Mary, University of London.
        </p>
        <p class="text-lg text-muted mt-5">
          When I am not working, I enjoy building websites from scratch, learning new technologies, playing chess, going to the gym and cooking new food from various cuisines.
        </p>
        <p class="text-lg text-muted mt-5">
          Here are some of the technologies I am currently working with:
        </p>
        <div class="flex flex-wrap gap-3 mt-6">
          <span
            v-for="skill in SKILLS"
            :key="skill"
            class="px-4 py-2 text-sm tracking-wide border border-line rounded-sm bg-ivory text-muted"
          >
            {{ skill }}
          </span>
        </div>
      </div>
      <div class="md:w-2/5 flex justify-center items-start">
        <img
          src="/larbi.JPG"
          alt="Larbi at his graduation"
          width="450"
          height="300"
          class="rounded-sm border border-line shadow-lg shadow-ink/5"
        />
      </div>
    </div>
  </section>
</template>
