// components/Hero.tsx
"use client"

import { motion } from "framer-motion"
import Image from "next/image";
import { IoMailOutline } from "react-icons/io5";

const Hero = () => {
  return (
    <section className="flex min-h-screen bg-blue-bg flex-1" id='hero'>
        <div className="m-auto max-container padding-container">
            <h1 className='text-8xl font-bold'>Hi, I'm Larbi.</h1>
            <h2 className='text-4xl mt-5'>I create stuff sometimes.</h2>
            <p className='text-lg mt-5'>I am a research analyst based in London. I have great interest in data science, artificial intelligence, full-stack development, and everything in between.</p>
            <motion.button 
                className="bg-black py-2 px-4 text-white text-xl font-semibold rounded-full mt-5"
                whileHover={{scale: 1.05}}
                whileTap={{ scale: 0.95}}
            >
              <a href="mailto:larbibelkhit@outlook.com">
                Get in touch
              </a>
            </motion.button>
        </div>
    </section>
  )
}

export default Hero

// src/components/Hero.vue
<template>
  <section class="relative flex min-h-screen overflow-hidden" id="hero">
    <div
      class="absolute inset-0 pointer-events-none"
      style="background: radial-gradient(ellipse at 75% 35%, color-mix(in srgb, var(--color-accent) 8%, transparent) 0%, transparent 60%)"
    />
    <div
      class="absolute inset-0 pointer-events-none"
      style="background: radial-gradient(ellipse at 15% 85%, color-mix(in srgb, var(--color-accent) 5%, transparent) 0%, transparent 50%)"
    />
    <div class="m-auto w-full max-w-5xl px-6 lg:px-8">
      <p class="text-[0.7rem] tracking-[0.35em] uppercase text-accent mb-5">
        Principal Analyst, AI · London
      </p>
      <h1 class="text-5xl md:text-7xl lg:text-8xl font-light leading-[1.05] tracking-tight">
        Hi, I'm Larbi.
      </h1>
      <h2 class="text-2xl md:text-3xl font-light text-muted mt-6">
        I turn complex AI research into clear market insight.
      </h2>
      <p class="text-lg text-muted mt-6 max-w-2xl">
        I am a Principal Analyst at ABI Research, based in London, leading
        research on artificial intelligence across telecoms, cloud and
        enterprise technology — with a background in 5G, 6G & Open RAN
        networks, and a broader interest in data science and full-stack
        development.
      </p>
      <div class="flex items-center gap-6 mt-10">
        <a
          href="mailto:larbibelkhit@outlook.com"
          class="bg-accent hover:bg-accent-dark py-3 px-7 text-white text-base tracking-wide rounded-sm transition-all duration-200 hover:scale-[1.03] active:scale-[0.97] inline-block"
        >
          Get in touch
        </a>
        <a
          href="#about"
          class="text-base tracking-wide text-muted hover:text-ink transition-colors duration-200"
        >
          More about me ↓
        </a>
      </div>
    </div>
  </section>
</template>
